(cl:in-package nxt_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CALIBRATION_OFFSET-VAL
          CALIBRATION_OFFSET
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          ANGULAR_VELOCITY_COVARIANCE-VAL
          ANGULAR_VELOCITY_COVARIANCE
))