/* Auto-generated by genmsg_cpp for file /home/xavier/ros_workspace/nxt/nxt_msgs/msg/Range.msg */
#ifndef NXT_MSGS_MESSAGE_RANGE_H
#define NXT_MSGS_MESSAGE_RANGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace nxt_msgs
{
template <class ContainerAllocator>
struct Range_ {
  typedef Range_<ContainerAllocator> Type;

  Range_()
  : header()
  , range(0.0)
  , range_min(0.0)
  , range_max(0.0)
  , spread_angle(0.0)
  {
  }

  Range_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , range(0.0)
  , range_min(0.0)
  , range_max(0.0)
  , spread_angle(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _range_type;
  double range;

  typedef double _range_min_type;
  double range_min;

  typedef double _range_max_type;
  double range_max;

  typedef double _spread_angle_type;
  double spread_angle;


  typedef boost::shared_ptr< ::nxt_msgs::Range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nxt_msgs::Range_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Range
typedef  ::nxt_msgs::Range_<std::allocator<void> > Range;

typedef boost::shared_ptr< ::nxt_msgs::Range> RangePtr;
typedef boost::shared_ptr< ::nxt_msgs::Range const> RangeConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::nxt_msgs::Range_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::nxt_msgs::Range_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace nxt_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::nxt_msgs::Range_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::nxt_msgs::Range_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::nxt_msgs::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "37a3243712d0ae8a8c4863ac843a1c75";
  }

  static const char* value(const  ::nxt_msgs::Range_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x37a3243712d0ae8aULL;
  static const uint64_t static_value2 = 0x8c4863ac843a1c75ULL;
};

template<class ContainerAllocator>
struct DataType< ::nxt_msgs::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "nxt_msgs/Range";
  }

  static const char* value(const  ::nxt_msgs::Range_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::nxt_msgs::Range_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float64 range\n\
float64 range_min\n\
float64 range_max\n\
float64 spread_angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::nxt_msgs::Range_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::nxt_msgs::Range_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::nxt_msgs::Range_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::nxt_msgs::Range_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.range);
    stream.next(m.range_min);
    stream.next(m.range_max);
    stream.next(m.spread_angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Range_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nxt_msgs::Range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::nxt_msgs::Range_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "range_min: ";
    Printer<double>::stream(s, indent + "  ", v.range_min);
    s << indent << "range_max: ";
    Printer<double>::stream(s, indent + "  ", v.range_max);
    s << indent << "spread_angle: ";
    Printer<double>::stream(s, indent + "  ", v.spread_angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // NXT_MSGS_MESSAGE_RANGE_H

